import "./style-v2.css";
import {STEP_LABELS,firstStep,nextStep,deadline,alertLevel,flowFor} from "./workflow.js";

let cfg={},session=JSON.parse(localStorage.getItem("cp_session")||"null"),profile=null,orders=[],profiles=[],partners=[],view="active",alertFilter="all",searchQuery="";
const params=new URLSearchParams(location.search),registration=params.get('register'),inviteToken=params.get('invite');
const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function api(path,opt={}){const r=await fetch(cfg.url+path,{...opt,headers:{apikey:cfg.key,Authorization:`Bearer ${session?.access_token||cfg.key}`,"Content-Type":"application/json",Prefer:"return=representation",...opt.headers}});const d=await r.json().catch(()=>[]);if(!r.ok)throw Error(d.message||d.msg||d.error||"操作失败");return d}
async function refresh(){if(!session)return render();[profile,orders,profiles,partners]=await Promise.all([api(`/rest/v1/profiles?id=eq.${session.user.id}&select=*`).then(x=>x[0]),api("/rest/v1/orders?select=*&order=order_date.desc,created_at.desc"),api("/rest/v1/profiles?select=*&order=created_at"),api("/rest/v1/partners?select=*&active=eq.true&order=name")]);render()}
function overdueDays(o){return o.step_deadline?Math.max(0,Math.floor((Date.now()-new Date(o.step_deadline))/86400000)+1):0}
function badge(o){const l=alertLevel(o.step_deadline);return `<span class="alert ${l}">${l==='normal'?'正常':l==='yellow'?'今日到期':l==='orange'?`超期 ${overdueDays(o)} 天`:`严重超期 ${overdueDays(o)} 天`}</span>`}
function render(){const follower=profile?.role==='follower',list=orders.filter(o=>(view==='archived'?o.archived_at:!o.archived_at)&&(alertFilter==='all'||alertLevel(o.step_deadline)===alertFilter)&&(!searchQuery||((o.order_no+' '+o.customer_info).toLowerCase().includes(searchQuery.toLowerCase())))),counts={yellow:0,orange:0,red:0};list.forEach(o=>{const l=alertLevel(o.step_deadline);if(counts[l]!=null)counts[l]++});
 $("#app").innerHTML=`<header><a class="brand"><b>CP</b><span>Cargo Pulse</span></a><nav>${session?`<span>${esc(session.user.email)}</span><strong>${follower?'跟单':'业务员'}</strong><button id="logout">退出</button>`:`<button id="login">登录</button>`}</nav></header><main>
 <section class="intro"><div><p class="kicker">ORDER OPERATIONS</p><h1>订单进度，<em>一目了然。</em></h1><p>从下单、生产到送达，每个节点独立计时并自动标记异常。</p></div>${follower?`<button class="primary" id="newOrder">＋ 创建订单</button>`:""}</section>
 ${session?`<section class="stats"><article data-alert="all"><small>进行中</small><b>${orders.filter(o=>!o.archived_at&&o.current_step!=='completed').length}</b></article><article class="yellow" data-alert="yellow"><small>今日到期</small><b>${counts.yellow}</b></article><article class="orange" data-alert="orange"><small>橙色异常</small><b>${counts.orange}</b></article><article class="red" data-alert="red"><small>红色异常</small><b>${counts.red}</b></article></section>
 <section class="searchbar"><span>⌕</span><input id="orderSearch" value="${esc(searchQuery)}" placeholder="搜索订单号、客户名称、电话或邮箱"></section><section class="toolbar"><div><button class="${view==='active'?'active':''}" data-view="active">进行中</button><button class="${view==='archived'?'active':''}" data-view="archived">已归档</button></div>${follower?`<button id="users">用户管理</button><button id="partners">工厂 / 货代</button>`:""}</section>
 <section class="orders">${list.length?list.map(o=>`<article class="order-card ${alertLevel(o.step_deadline)}" data-order="${o.id}"><div><span class="order-no">${esc(o.order_no)}</span>${badge(o)}</div><h3>${esc(o.product_name)} <small>× ${o.quantity}</small></h3><p>${esc(o.customer_info)}</p><footer><span>当前：<b>${STEP_LABELS[o.current_step]||o.current_step}</b></span><span>${o.step_deadline?`截止 ${new Date(o.step_deadline).toLocaleDateString('zh-CN')}`:'等待设置'}</span><span>业务员：${esc(o.business_name||'未分配')}</span></footer></article>`).join(""):`<div class="empty">暂无订单</div>`}</section>`:`<section class="signin"><h2>登录后查看订单</h2><p>首个注册账户自动成为跟单，后续账户默认为业务员。</p><button class="primary" id="login2">登录 / 注册</button></section>`}</main>
 <dialog id="auth"><form id="authForm"><button class="x" type="button">×</button><h2>登录 Cargo Pulse</h2><label>邮箱<input name="email" type="email" required></label><label>密码<input name="password" type="password" minlength="6" required></label><p class="error"></p><div class="actions"><button name="mode" value="signup">注册</button><button class="primary" name="mode" value="login">登录</button></div></form></dialog>
 <dialog id="orderDialog"></dialog><dialog id="detail"></dialog><dialog id="manage"></dialog>`;bind()}
function orderForm(){const businesses=profiles.filter(p=>p.role==='business'),fac=partners.filter(p=>p.kind==='factory'),fw=partners.filter(p=>p.kind==='forwarder');return `<form id="orderForm"><button class="x" type="button">×</button><h2>创建订单</h2><div class="grid"><label>后台订单号 *<input name="order_no" required></label><label>下单日期 *<input name="order_date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>产品名称 *<input name="product_name" required></label><label>尺寸 *<input name="size" required></label><label>数量 *<input name="quantity" type="number" min="1" required></label><label class="wide">客户信息（姓名、地址、联系方式）*<textarea name="customer_info" required></textarea></label><label>风机<input name="blower"></label><label>负责业务员 *<select name="business_name" required><option value="" disabled selected>请选择</option><option>Ella</option><option>Sherry</option><option>Demi</option><option>Rayna</option></select></label><label>库存 / 生产<select name="inventory_mode"><option value="production">下单生产</option><option value="stock">现有库存</option></select></label><label>工厂<input name="factory_name" list="factoryList"></label><label>效果图<select name="needs_rendering"><option value="false">不画效果图</option><option value="true">画效果图</option></select></label><label>发货方式<select name="shipping_mode"><option value="">稍后选择</option><option value="domestic_express">国内快递</option><option value="domestic_sea">国内发海运</option><option value="overseas_warehouse">海外仓发货</option></select></label><label>海运区域<select name="sea_region"><option value="">不适用</option><option value="non_europe">非欧洲</option><option value="europe">欧洲</option></select></label><label>海外仓方式<select name="overseas_method"><option value="">不适用</option><option value="express">快递</option><option value="truck">卡派</option></select></label><label class="wide">订单要求<textarea name="requirements"></textarea></label><label class="wide">产品图片<input name="images" type="file" accept="image/*" multiple></label></div><datalist id="factoryList">${fac.map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist><datalist id="forwarderList">${fw.map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist><p class="error"></p><button class="primary">保存订单</button></form>`}
async function uploadImages(orderId,files){for(const file of files){const path=`${orderId}/${crypto.randomUUID()}-${file.name}`;const r=await fetch(`${cfg.url}/storage/v1/object/order-images/${path}`,{method:'POST',headers:{apikey:cfg.key,Authorization:`Bearer ${session.access_token}`,'Content-Type':file.type},body:file});if(!r.ok)throw Error('图片上传失败');await api('/rest/v1/order_images',{method:'POST',body:JSON.stringify({order_id:orderId,object_path:path,file_name:file.name})})}}
function detailHtml(o){const follower=profile.role==='follower',flow=flowFor(o),pos=Math.max(0,flow.indexOf(o.current_step)),pct=flow.length>1?Math.round(pos/(flow.length-1)*100):100;return `<div class="detail"><button class="x" type="button">×</button><div class="progress"><div style="width:${pct}%"></div></div><div class="progress-labels"><span>${STEP_LABELS[flow[0]]}</span><b>${pct}% · ${STEP_LABELS[o.current_step]}</b><span>${STEP_LABELS[flow[flow.length-1]]}</span></div><div class="detail-head"><div><p class="kicker">${esc(o.order_no)}</p><h2>${esc(o.product_name)} × ${o.quantity}</h2></div>${badge(o)}</div><dl><div><dt>当前步骤</dt><dd>${STEP_LABELS[o.current_step]}</dd></div><div><dt>阶段截止</dt><dd>${o.step_deadline?new Date(o.step_deadline).toLocaleString('zh-CN'):'无'}</dd></div><div><dt>尺寸</dt><dd>${esc(o.size)}</dd></div><div><dt>客户信息</dt><dd>${esc(o.customer_info)}</dd></div><div><dt>工厂</dt><dd>${esc(o.factory_name||'-')}</dd></div><div><dt>货代</dt><dd>${esc(o.forwarder_name||'-')}</dd></div><div><dt>订单要求</dt><dd>${esc(o.requirements||'-')}</dd></div></dl>${follower?`<div class="actions">${o.current_step!=='completed'?`<button class="primary" id="advance">确认完成当前步骤</button>`:''}${!o.archived_at?`<button id="archive">归档订单</button>`:''}</div>`:''}</div>`}
function bind(){$('#orderSearch')?.addEventListener('input',e=>{searchQuery=e.target.value;render();$('#orderSearch')?.focus()});document.querySelectorAll('[data-alert]').forEach(b=>b.onclick=()=>{alertFilter=b.dataset.alert;view='active';render()});document.querySelectorAll('.x').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#logout')?.addEventListener('click',()=>{localStorage.removeItem('cp_session');session=null;profile=null;orders=[];render()});$('#login')?.addEventListener('click',()=>$('#auth').showModal());$('#login2')?.addEventListener('click',()=>$('#auth').showModal());document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
 $('#authForm').onsubmit=async e=>{e.preventDefault();let d=new FormData(e.target),mode=e.submitter.value;try{let r=await api(mode==='signup'?'/auth/v1/signup':'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:d.get('email'),password:d.get('password'),data:{follower_invite:inviteToken||''}})});if(!r.access_token)throw Error('请先完成邮箱验证，再登录');session=r;localStorage.setItem('cp_session',JSON.stringify(r));await refresh()}catch(x){e.target.querySelector('.error').textContent=x.message}};
 $('#newOrder')?.addEventListener('click',()=>{let d=$('#orderDialog');d.innerHTML=orderForm();d.showModal();d.querySelector('.x').onclick=()=>d.close();d.querySelector('form').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),payload=Object.fromEntries([...f].filter(([k])=>k!=='images'));payload.quantity=Number(payload.quantity);payload.needs_rendering=payload.needs_rendering==='true';['shipping_mode','sea_region','overseas_method'].forEach(k=>{if(!payload[k])payload[k]=null});let step=firstStep(payload);payload.current_step=step.key;payload.step_deadline=deadline(step.days);try{let [o]=await api('/rest/v1/orders',{method:'POST',body:JSON.stringify(payload)});await api('/rest/v1/order_events',{method:'POST',body:JSON.stringify({order_id:o.id,step_key:step.key,started_at:o.step_started_at,deadline_at:o.step_deadline})});await uploadImages(o.id,f.getAll('images').filter(x=>x.size));await refresh()}catch(x){e.target.querySelector('.error').textContent=x.message}}});
 document.querySelectorAll('[data-order]').forEach(c=>c.onclick=()=>{let o=orders.find(x=>x.id===c.dataset.order),d=$('#detail');d.innerHTML=detailHtml(o);d.showModal();d.querySelector('.x').onclick=()=>d.close();d.querySelector('#archive')?.addEventListener('click',async()=>{await api(`/rest/v1/orders?id=eq.${o.id}`,{method:'PATCH',body:JSON.stringify({archived_at:new Date().toISOString()})});await refresh()});d.querySelector('#advance')?.addEventListener('click',async()=>{let forwarder=o.forwarder_name;if(o.current_step==='ready_to_ship'){forwarder=prompt('请选择或填写货代：\n'+partners.filter(p=>p.kind==='forwarder').map(p=>p.name).join('、'),forwarder||'');if(!forwarder)return;await api('/rest/v1/orders?id=eq.'+o.id,{method:'PATCH',body:JSON.stringify({forwarder_name:forwarder})});}let n=nextStep(o,o.current_step),now=new Date().toISOString();await api(`/rest/v1/order_events?order_id=eq.${o.id}&completed_at=is.null`,{method:'PATCH',body:JSON.stringify({completed_at:now,completed_by:session.user.id})});await api('/rest/v1/order_events',{method:'POST',body:JSON.stringify({order_id:o.id,step_key:n.key,started_at:now,deadline_at:deadline(n.days)})});await api(`/rest/v1/orders?id=eq.${o.id}`,{method:'PATCH',body:JSON.stringify({current_step:n.key,step_started_at:now,step_deadline:deadline(n.days),updated_at:now})});await refresh()})});
 $('#users')?.addEventListener('click',()=>showInvites());if(!session&&registration)$('#auth').showModal();$('#partners')?.addEventListener('click',()=>managePartners())}
function manageUsers(){let d=$('#manage');d.innerHTML=`<div class="detail"><button class="x">×</button><h2>用户管理</h2>${profiles.map(p=>`<label>${esc(p.email)}<select data-role="${p.id}"><option value="business" ${p.role==='business'?'selected':''}>业务员</option><option value="follower" ${p.role==='follower'?'selected':''}>跟单</option></select></label>`).join('')}</div>`;d.showModal();d.querySelector('.x').onclick=()=>d.close();d.querySelectorAll('[data-role]').forEach(s=>s.onchange=()=>api(`/rest/v1/profiles?id=eq.${s.dataset.role}`,{method:'PATCH',body:JSON.stringify({role:s.value})}))}
function managePartners(){let d=$('#manage');d.innerHTML=`<div class="detail"><button class="x">×</button><h2>工厂 / 货代</h2>${partners.map(p=>`<p>${p.kind==='factory'?'工厂':'货代'} · ${esc(p.name)}</p>`).join('')}<form id="partnerForm"><select name="kind"><option value="factory">工厂</option><option value="forwarder">货代</option></select><input name="name" required placeholder="名称"><button class="primary">新增</button></form></div>`;d.showModal();d.querySelector('.x').onclick=()=>d.close();d.querySelector('form').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);await api('/rest/v1/partners',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await refresh()}}

async function showInvites(){let row=await api('/rest/v1/app_settings?key=eq.follower_invite&select=value').then(function(x){return x[0]});let businessLink=location.origin+'/?register=business',followerLink=location.origin+'/?register=follower&invite='+(row?row.value:'');let d=$('#manage');let users=profiles.map(function(p){return '<label>'+esc(p.email)+'<select data-role="'+p.id+'"><option value="business" '+(p.role==='business'?'selected':'')+'>业务员</option><option value="follower" '+(p.role==='follower'?'selected':'')+'>跟单</option></select></label>'}).join('');d.innerHTML='<div class="detail"><button class="x">×</button><h2>用户管理</h2><label>业务员注册链接<input readonly value="'+businessLink+'"></label><label>跟单邀请链接（请勿公开）<input readonly value="'+followerLink+'"></label><p>点击输入框即可复制。跟单链接拥有全部编辑权限，只发给可信人员。</p>'+users+'</div>';d.showModal();d.querySelector('.x').onclick=function(){d.close()};d.querySelectorAll('input[readonly]').forEach(function(i){i.onclick=function(){i.select();navigator.clipboard.writeText(i.value)}});d.querySelectorAll('[data-role]').forEach(function(s){s.onchange=function(){api('/rest/v1/profiles?id=eq.'+s.dataset.role,{method:'PATCH',body:JSON.stringify({role:s.value})})}})}
fetch('/api/config',{cache:'no-store'}).then(r=>r.json()).then(x=>{cfg=x;return refresh()}).catch(()=>render());
