import "./style.css";

let cfg={url:"",key:""}, session=JSON.parse(localStorage.getItem("cp_session")||"null"), shipments=[], filter="全部";
const $=s=>document.querySelector(s);

async function request(path,options={}){
  const r=await fetch(cfg.url+path,{...options,headers:{apikey:cfg.key,Authorization:`Bearer ${session?.access_token||cfg.key}`,"Content-Type":"application/json",Prefer:"return=representation",...options.headers}});
  const data=await r.json().catch(()=>[]); if(!r.ok) throw new Error(data.message||data.msg||"操作失败"); return data;
}
async function init(){cfg=await fetch("/api/config",{cache:"no-store"}).then(r=>r.json());if(session)shipments=await request("/rest/v1/shipments?select=*&order=updated_at.desc");render();}
function statusClass(s){return ({运输中:"moving",待提货:"waiting",异常:"risk",已签收:"done"})[s]||"waiting"}
function render(){
  const shown=shipments.filter(s=>filter==="全部"||s.status===filter), active=shipments.filter(s=>s.status!=="已签收").length;
  $("#app").innerHTML=`<header class="topbar"><a class="brand"><span class="brand-mark">CP</span><span>Cargo Pulse</span></a><div class="top-actions"><span class="sync"><i></i>Supabase 已连接</span>${session?`<small>${session.user.email}</small><button class="avatar" id="logout">退</button>`:`<button class="login-link" id="login">登录</button>`}</div></header>
  <main><section class="hero"><div><p class="eyebrow">物流控制台</p><h1>每一票货，<br><em>都在视线内。</em></h1><p class="intro">安全管理运输状态、预计到达与异常事项。</p></div><button class="primary" id="add">＋ 新建物流单</button></section>
  ${session?`<section class="metrics"><article><span>进行中</span><strong>${active}</strong><small>票在途货物</small></article><article><span>待提货</span><strong>${shipments.filter(s=>s.status==="待提货").length}</strong><small>等待处理</small></article><article class="risk-card"><span>需要处理</span><strong>${shipments.filter(s=>s.status==="异常").length}</strong><small>票异常事项</small></article><article><span>已签收</span><strong>${shipments.filter(s=>s.status==="已签收").length}</strong><small>累计完成</small></article></section>`:`<section class="auth-callout"><div><p class="eyebrow">PRIVATE WORKSPACE</p><h2>登录后开始管理物流单</h2><p>每个账户只能查看和修改自己的数据。</p></div><button class="primary" id="login2">登录 / 注册</button></section>`}
  <section class="workspace"><div class="section-head"><div><p class="eyebrow">SHIPMENT BOARD</p><h2>物流看板</h2></div></div><div class="filters">${["全部","待提货","运输中","异常","已签收"].map(x=>`<button class="${filter===x?"active":""}" data-filter="${x}">${x}<b>${x==="全部"?shipments.length:shipments.filter(s=>s.status===x).length}</b></button>`).join("")}</div><div class="table-wrap"><table><thead><tr><th>物流单</th><th>路线 / 客户</th><th>状态</th><th>预计到达</th><th>承运商</th><th></th></tr></thead><tbody>${!session?`<tr><td class="empty" colspan="6">请先登录</td></tr>`:shown.length?shown.map(s=>`<tr><td><strong>${s.tracking_no}</strong></td><td><strong>${s.route}</strong><small>${s.customer}</small></td><td><select data-status="${s.id}" class="status-select ${statusClass(s.status)}">${["待提货","运输中","异常","已签收"].map(x=>`<option ${x===s.status?"selected":""}>${x}</option>`).join("")}</select></td><td>${new Date(s.eta).toLocaleDateString("zh-CN")}</td><td>${s.carrier}</td><td><button class="delete" data-delete="${s.id}">×</button></td></tr>`).join(""):`<tr><td class="empty" colspan="6">还没有物流单</td></tr>`}</tbody></table></div></section></main>
  <dialog id="auth"><form id="authForm"><div class="dialog-head"><h2>登录 Cargo Pulse</h2><button type="button" class="close">×</button></div><label>邮箱<input name="email" type="email" required></label><label>密码<input name="password" type="password" minlength="6" required></label><p class="form-error"></p><div class="dialog-actions"><button class="secondary" name="mode" value="signup">注册</button><button class="primary" name="mode" value="login">登录</button></div></form></dialog>
  <dialog id="shipment"><form id="shipmentForm"><div class="dialog-head"><h2>新建物流单</h2><button type="button" class="close">×</button></div><div class="form-grid"><label>物流单号<input name="tracking_no" required></label><label>承运商<input name="carrier" required></label><label>起点<input name="origin" required></label><label>终点<input name="destination" required></label><label>客户<input name="customer" required></label><label>预计到达<input name="eta" type="date" required></label><label>状态<select name="status"><option>待提货</option><option>运输中</option><option>异常</option><option>已签收</option></select></label></div><p class="form-error"></p><button class="primary">保存</button></form></dialog>`;bind();
}
function bind(){
  document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});
  document.querySelectorAll(".close").forEach(b=>b.onclick=()=>b.closest("dialog").close());
  $("#login")?.addEventListener("click",()=>$("#auth").showModal()); $("#login2")?.addEventListener("click",()=>$("#auth").showModal());
  $("#logout")?.addEventListener("click",()=>{session=null;shipments=[];localStorage.removeItem("cp_session");render()});
  $("#add").onclick=()=>session?$("#shipment").showModal():$("#auth").showModal();
  $("#authForm").onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target),mode=e.submitter.value;try{const path=mode==="signup"?"/auth/v1/signup":"/auth/v1/token?grant_type=password";const result=await request(path,{method:"POST",body:JSON.stringify({email:d.get("email"),password:d.get("password")})});if(!result.access_token)throw new Error("请查收验证邮件，然后登录");session=result;localStorage.setItem("cp_session",JSON.stringify(result));shipments=await request("/rest/v1/shipments?select=*&order=updated_at.desc");render()}catch(err){e.target.querySelector(".form-error").textContent=err.message}};
  $("#shipmentForm").onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target);try{await request("/rest/v1/shipments",{method:"POST",body:JSON.stringify({tracking_no:d.get("tracking_no"),carrier:d.get("carrier"),route:`${d.get("origin")} → ${d.get("destination")}`,customer:d.get("customer"),eta:d.get("eta"),status:d.get("status")})});shipments=await request("/rest/v1/shipments?select=*&order=updated_at.desc");render()}catch(err){e.target.querySelector(".form-error").textContent=err.message}};
  document.querySelectorAll("[data-status]").forEach(s=>s.onchange=async()=>{await request(`/rest/v1/shipments?id=eq.${s.dataset.status}`,{method:"PATCH",body:JSON.stringify({status:s.value,updated_at:new Date().toISOString()})});shipments=await request("/rest/v1/shipments?select=*&order=updated_at.desc");render()});
  document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{if(confirm("确定删除？")){await request(`/rest/v1/shipments?id=eq.${b.dataset.delete}`,{method:"DELETE"});shipments=await request("/rest/v1/shipments?select=*&order=updated_at.desc");render()}});
}
init().catch(()=>render());
